spring:
  application:
    name: blog
  flyway:
    locations: classpath:/db/flyway # migration ???? ???? directory
    sql-migration-suffixes: sql        # ?? ???
    baseline-on-migrate: true          # flyway_schema_history ???? ???? ???? ??
    baseline-version: 0                # ?? ?? ??
